"""
Tests for pydepgate.enrichers._asn1.

The cert fixtures (CERT_VANILLA_RSA2048, CERT_RICH_SAN,
CERT_SUSPICIOUS) were generated once by build_cert_fixtures.py
using the cryptography library and frozen here as hex literals.
Re-running build_cert_fixtures.py would produce different bytes
(different signatures, different timestamps), so do not regenerate
the fixtures without also updating the assertions below.

Coverage map (one xref per public function/method tested):

  read_tlv                        TestReadTLV
  read_oid                        TestReadOID
  read_integer_unsigned           TestReadIntegerUnsigned
  read_integer_signed             TestReadIntegerSigned
  read_utf8_string                TestReadUtf8String
  read_printable_string           TestReadPrintableString
  read_ia5_string                 TestReadIa5String
  read_bmp_string                 TestReadBmpString
  read_t61_string                 TestReadT61String
  read_utc_time                   TestReadUtcTime
  read_generalized_time           TestReadGeneralizedTime
  looks_like_der                  TestLooksLikeDER
  classify (anomaly paths)        TestClassifyAnomalies
  classify (SPKI)                 TestClassifySPKI
  classify (X.509 cert)           TestClassifyX509VanillaCert
                                  TestClassifyX509RichSAN
                                  TestClassifyX509Suspicious
  FormatContext (marker)          TestFormatContextMarker

The X.509 cert tests use real self-signed certificates rather than
hand-crafted DER, on the theory that a parser that only handles
hand-crafted inputs has been hand-fitted to the parser. Real certs
(even ones we generate ourselves) catch encoder choices we did not
think to test for.

Cert tests use setUpClass so classify() runs once per cert across
the entire test class. Other tests are cheap enough to leave in
per-test scope.
"""

from __future__ import annotations

import dataclasses
import os
import pickle
import unittest

from pydepgate.enrichers._asn1 import (
    ASN1ParseError,
    DERAnomaly,
    DERClassification,
    FormatContext,
    SubjectAltName,
    TAG_BIT_STRING,
    TAG_INTEGER,
    TAG_OID,
    TAG_SEQUENCE,
    TAG_UTC_TIME,
    TagInfo,
    X509Extension,
    classify,
    looks_like_der,
    read_bmp_string,
    read_generalized_time,
    read_ia5_string,
    read_integer_signed,
    read_integer_unsigned,
    read_oid,
    read_printable_string,
    read_t61_string,
    read_tlv,
    read_utc_time,
    read_utf8_string,
)


# ---------------------------------------------------------------------------
# Cert fixtures (generated by build_cert_fixtures.py; see module docstring).
# ---------------------------------------------------------------------------

# CERT_VANILLA_RSA2048: 796 bytes
# CN=test.example.com, O=Test Org, OU=Test Unit, C=US
# Serial 12345, validity 2025-01-01 to 2026-01-01 (UTCTime), no extensions.
CERT_VANILLA_RSA2048 = bytes.fromhex(
    "3082031830820200a00302010202023039300d06092a864886f70d01010b0500"
    "304f3119301706035504030c10746573742e6578616d706c652e636f6d311130"
    "0f060355040a0c0854657374204f726731123010060355040b0c095465737420"
    "556e6974310b3009060355040613025553301e170d3235303130313030303030"
    "305a170d3236303130313030303030305a304f3119301706035504030c107465"
    "73742e6578616d706c652e636f6d3111300f060355040a0c0854657374204f72"
    "6731123010060355040b0c095465737420556e6974310b300906035504061302"
    "555330820122300d06092a864886f70d01010105000382010f003082010a0282"
    "010100d908ab6d2b97d4ec7ae37fe55681449c87520ee06a128685039581fdf4"
    "678519f4c0bbb47c33f82632c2dc489ba3492a46184fe0904fd5d8c16c017000"
    "60c7ebf95fbb8e0fe0b9e5e86a150c0060c99eb40e8e055b7b19b0cdaa3a2bbe"
    "84234bca4e765d7a18aa00c9c39c47d96af4656227e4b99b4648e4245ed1e88a"
    "ed3739ed9e919488f0c45607d5794663511336ef3a8dff59c45e86e8bc0153d6"
    "3bab94d6b8ff23777fd83ca71c556e91be8ba02ff8d687a0a525e8d1f794a705"
    "c7466069d7186707bc1721e8d3ff7664d9222b362bb53f32c863982c309678ac"
    "cb83ffc66e2e4b14b4b4b974ea06a9ffcd58ca98493ba250ec6bdc9eb99428a6"
    "21d4cd0203010001300d06092a864886f70d01010b05000382010100934726c3"
    "e81d9355d94aefce6d37d049706d1a617a115e5900e49a5da8867657d107321c"
    "29f4df6fd28caa5f064b04969b36ba6dd336e49358f133040b9212cc338ffd28"
    "7a6eacba31b089889648244933c90ef01f1d1d41068185c7072dd9c46e8a0b46"
    "dc1c470b725d31be0d93239b0b258300d7844119a50ededf9451bce9d4ae5ef3"
    "9c917cfb4e5a710a7852026a3da8dab242a709ce2f6846c66d96a23e90b87656"
    "9198e5a9b0b55bde66483e92b666ba662b91e130a8ab3479ceaf1ffaf2284006"
    "8ecf5fcd72418628d6b3b999daa772e52340d1c35c292aaadfc2a413089e26af"
    "7cfed8e0f15e5e6f93578f4af3ddfbf10846574fa4fc9d55ea017987"
)

# CERT_RICH_SAN: 904 bytes
# CN=richcert.example.com. SAN has 2 dns + 1 uri + 1 email + 1 ip.
# Four extensions: SAN, BasicConstraints (critical), KeyUsage (critical),
# ExtKeyUsage.
CERT_RICH_SAN = bytes.fromhex(
    "308203843082026ca0030201020203010932300d06092a864886f70d01010b05"
    "003032311d301b06035504030c1472696368636572742e6578616d706c652e63"
    "6f6d3111300f060355040a0c0852696368204f7267301e170d32353031303130"
    "30303030305a170d3237303130313030303030305a3032311d301b0603550403"
    "0c1472696368636572742e6578616d706c652e636f6d3111300f060355040a0c"
    "0852696368204f726730820122300d06092a864886f70d01010105000382010f"
    "003082010a0282010100d908ab6d2b97d4ec7ae37fe55681449c87520ee06a12"
    "8685039581fdf4678519f4c0bbb47c33f82632c2dc489ba3492a46184fe0904f"
    "d5d8c16c01700060c7ebf95fbb8e0fe0b9e5e86a150c0060c99eb40e8e055b7b"
    "19b0cdaa3a2bbe84234bca4e765d7a18aa00c9c39c47d96af4656227e4b99b46"
    "48e4245ed1e88aed3739ed9e919488f0c45607d5794663511336ef3a8dff59c4"
    "5e86e8bc0153d63bab94d6b8ff23777fd83ca71c556e91be8ba02ff8d687a0a5"
    "25e8d1f794a705c7466069d7186707bc1721e8d3ff7664d9222b362bb53f32c8"
    "63982c309678accb83ffc66e2e4b14b4b4b974ea06a9ffcd58ca98493ba250ec"
    "6bdc9eb99428a621d4cd0203010001a381a230819f30600603551d1104593057"
    "8210616c74312e6578616d706c652e636f6d8210616c74322e6578616d706c65"
    "2e636f6d861868747470733a2f2f6578616d706c652e636f6d2f636572748111"
    "61646d696e406578616d706c652e636f6d8704c000022a300c0603551d130101"
    "ff04023000300e0603551d0f0101ff0404030205a0301d0603551d2504163014"
    "06082b0601050507030106082b06010505070302300d06092a864886f70d0101"
    "0b050003820101003dbd4623ee1525f8993b9d306269c517c5fe7c18eb77fdee"
    "28858adee1c50717b76846735fd8abbb854718eff44ac8c3890c0e251e8fc57f"
    "4341d6c89bae2e147fe4fa66353f16c33c973be568e9891e685a6a2d61f8b96b"
    "edae5bb92032e8cf91359041e1fe6203d5964f9d9acb18c0b42a7e770d5e043d"
    "97edb4a0044f10028ee3e277f7e6a73726d6fb8f5f3216bf1b159c2a98aa510c"
    "b0a29f535190e4cb78fbd4c96c5311a248185f96e680dc210e927051090d1a64"
    "87cc573e65b2fd6663a37bab4843d66c0ebdeb66f29f28dc1e73ad2458ab6fca"
    "90198ef5f7edb257a0bd022a3e3dc69901dc9807a9f622bdb69d2c6e429e1438"
    "aa05f88f7b941d18"
)

# CERT_SUSPICIOUS: 1465 bytes
# RSA-4096. CN is 50 chars of pseudo-random alphanumerics.
# Serial 0xdeadbeefcafebabe. Validity ends 9999-12-31 23:59:59
# (encoded as GeneralizedTime since it exceeds UTCTime's 2049 cap).
# SAN contains a normal DNS name and an otherName with custom OID.
# Critical extension with unrecognized OID.
CERT_SUSPICIOUS = bytes.fromhex(
    "308205b53082039da003020102020900deadbeefcafebabe300d06092a864886"
    "f70d01010b05003057313c303a06035504030c3378374b70396d5a346e517254"
    "327657793841624364456647684a6b4c6d4e6f507152735475567758795a3132"
    "3334353637383931173015060355040a0c0e537573706963696f7573204f7267"
    "3020170d3235303130313030303030305a180f39393939313233313233353935"
    "395a3057313c303a06035504030c3378374b70396d5a346e5172543276577938"
    "41624364456647684a6b4c6d4e6f507152735475567758795a31323334353637"
    "383931173015060355040a0c0e537573706963696f7573204f72673082022230"
    "0d06092a864886f70d01010105000382020f003082020a02820201008eac4b6c"
    "11e0ece26af35534a2b7d9e82851d3fc169d736bd1cecde6fb93d5b7126cdbef"
    "59351f29aa01224efaa090e5aa2a9874587473264de752c0b3212a9754ad0599"
    "6d8d290d0a41f8966124ab4b071aa8cd93fd395b12a13563bc99e0a2e9eb76d5"
    "ae11716075aa8daef632d0191b27dee688c23823ec14f27d46f61a4963af0267"
    "c1d182785622a38b42b51aa5c845152a178af6fa58f083534314c9d1f371fd26"
    "da6cb887095ac622560a974a64b0ad209aa21b0b485c195634202342a0167a4f"
    "ca43155b43e6435f6822d92341184e9559a62a0406bdc34da05cca3cd7c7da48"
    "5ff10e3af827662b0b3e58a0e0dbcf11aaa5992a766e333ca31668bfd662a040"
    "8b7c55aeb021848a869cedb7e7b9723117279b7b6b851fbcad4c89216766bb9e"
    "df0289ee81e681fd88f1aec71731a7706039ace149dc0ed94ab11019aabdfac7"
    "a39bc1901cfbad0c21d8387fbe50a00712e291671b426281aeb90f53af094857"
    "7e999438f37e285e35e5fd9bde84feb285b85cbd44134f90c897de06dd9455ac"
    "4de71ff9a3288875de2bba3ceb073ab20194936564a328ab384fb869b6b3b799"
    "39844318595ac700bafa111ee7b8e3c04e153fc4ae4ef0ff7df3aa3f7c6c4d86"
    "bbb0f3a596504e0ab236417c5c19942d0738182dac4a998b7c3857258613e0c9"
    "c0d56f8add6c120fe2ef9c86182fcebea06e46d47cb1496ebf00994d02030100"
    "01a38181307f30480603551d110441303f8219746f74616c6c796e6f74616332"
    "2e6578616d706c652e636f6da022060b2b06010401868d1f010203a013041161"
    "72626974726172792d7061796c6f61643033060b2b06010401868d1f07070701"
    "01ff04210420756e6b6e6f776e2d637269746963616c2d657874656e73696f6e"
    "2d64617461300d06092a864886f70d01010b050003820201003b1fa9286d644f"
    "64b4ba21cdfd46d9fbe7a37074eee233716319ac58e1b7506d1c74a544303672"
    "941f7d32ee7c4b4292a160709d12e9358358d5e8fe97863475c7df2716d36355"
    "2c771a905a7119fa6a69f3efea3d6be14322a57cb7f770a3658e0413e463e74a"
    "ae40164e4b65595404c1c35b972a7da50f9d596e1ebd6789666e046cb1eb5f44"
    "9a29ee6a8c51ca3ce69c44972ca116891b0898498a0b6225b8d3e4cf13430239"
    "01fedae42fb8570fc9e56ceec7191c7f016857edf3bce56d0945c7c560eccf9d"
    "41036c60b7ab23a9dbc53f6774acded2926cdf993c6008e5f4b92d0108d94804"
    "aee0566361a8e3d4dd67cb2b8c6a0c8a2e74fe9b0c76daa18337309b23408312"
    "890d2aa7e8583bde19716a907863b79a743556c71d437296e3dd03e0576c56ba"
    "d1ef9a9cfd2244a2713dff5b871f35b999b5a9afdee3aeca704be742b9689ed5"
    "5f690918f02d317c2742048297391d62110e37302617f2ce0937050010175320"
    "d7206671d538f412666f7c026be7cd08c8bc54fe013a33b88a452bb3e5930f52"
    "d0dbdea767dc659f683ca93881e5ded89fba6fa0846583c3534db1b7bb3495ac"
    "566fd3f4a39673ce548a39df0286ede349bba599e29826628ac29924f1cc842a"
    "72add725bcfbae43cbbd94c7c9a5b9bc8f55f139e3ec1d77e1b730a7a3197cb6"
    "e6320680e25981adec1b74e1c1ebf4ec123809a556dec382b6"
)

# SPKI_RSA_2048: 294 bytes. A standalone SubjectPublicKeyInfo (the
# bytes you get from `openssl rsa -pubout -outform DER`). Distinct
# from any of the cert fixtures so the SPKI dispatch path is
# exercised independently of the cert dispatch path.
SPKI_RSA_2048 = bytes.fromhex(
    "30820122300d06092a864886f70d01010105000382010f003082010a02820101"
    "00c71d3ed4303850901787f130a8ce60a09f567a086e6ec4d52bf49785db3cf2"
    "ce9862dc473590b67c0a30416d4b8133068d1e255a865b7a3d56c7ecabcc1b38"
    "4bbca223cabfa896cc961f4be0656be9e5a3102018239b8051e125edfebb9730"
    "65222098a8e39d46d40d899f955db1aecf56da277ef7276f57917968adee239f"
    "910c2e29f401aebdf7206745f8e7403463221f2d7d029f7a86247093ac76a318"
    "083b8bb3dac9663b54b09310c7d165a2583b68ea36b0fc58676d0ae293fa6cb8"
    "44cc89e9394f4b1d5ea443187367873a0c707bf1b9ca571bb5942fa2e145e06c"
    "f77b3368518aeaa0c1a54f1a8c3c51867b74620e77f23afed02c1f096ad749a0"
    "e30203010001"
)


# ---------------------------------------------------------------------------
# TLV reader
# ---------------------------------------------------------------------------

class TestReadTLV(unittest.TestCase):
    """Coverage of read_tlv: short/long-form length, overrun, recovery."""

    def test_short_form_length_basic(self):
        # SEQUENCE { } empty: 30 00
        anomalies: list[DERAnomaly] = []
        tag, length, body, end = read_tlv(b"\x30\x00", 0, anomalies, "test")
        self.assertEqual(tag, TAG_SEQUENCE)
        self.assertEqual(length, 0)
        self.assertEqual(body, 2)
        self.assertEqual(end, 2)
        self.assertEqual(anomalies, [])

    def test_short_form_length_with_content(self):
        # INTEGER 0x42: 02 01 42
        anomalies: list[DERAnomaly] = []
        tag, length, body, end = read_tlv(
            b"\x02\x01\x42", 0, anomalies, "test",
        )
        self.assertEqual(tag, TAG_INTEGER)
        self.assertEqual(length, 1)
        self.assertEqual(body, 2)
        self.assertEqual(end, 3)
        self.assertEqual(anomalies, [])

    def test_long_form_length_one_octet(self):
        # SEQUENCE of length 200: 30 81 c8 followed by 200 bytes
        body_bytes = b"\x00" * 200
        buf = b"\x30\x81\xc8" + body_bytes
        anomalies: list[DERAnomaly] = []
        tag, length, body, end = read_tlv(buf, 0, anomalies, "test")
        self.assertEqual(tag, TAG_SEQUENCE)
        self.assertEqual(length, 200)
        self.assertEqual(body, 3)
        self.assertEqual(end, 203)
        self.assertEqual(anomalies, [])

    def test_long_form_length_two_octets(self):
        # SEQUENCE of length 1000: 30 82 03 e8 followed by 1000 bytes
        body_bytes = b"\x00" * 1000
        buf = b"\x30\x82\x03\xe8" + body_bytes
        anomalies: list[DERAnomaly] = []
        tag, length, body, end = read_tlv(buf, 0, anomalies, "test")
        self.assertEqual(length, 1000)
        self.assertEqual(end, 1004)
        self.assertEqual(anomalies, [])

    def test_length_overrun_clamps_to_buffer(self):
        # Tag says 100 bytes follow; only 5 actually present.
        buf = b"\x30\x64hello"  # 0x64 = 100
        anomalies: list[DERAnomaly] = []
        _, _, _, end = read_tlv(buf, 0, anomalies, "test")
        self.assertEqual(end, len(buf))
        self.assertTrue(any(a.kind == "length_overrun" for a in anomalies))

    def test_indefinite_length_recovers(self):
        # 0x80 = indefinite-length form (BER, not DER).
        buf = b"\x30\x80\x02\x01\x01\x00\x00"
        anomalies: list[DERAnomaly] = []
        _, _, _, end = read_tlv(buf, 0, anomalies, "test")
        self.assertEqual(end, len(buf))
        self.assertTrue(
            any(a.kind == "indefinite_length" for a in anomalies)
        )

    def test_non_minimal_length_recorded(self):
        # Length 5 encoded as long-form (81 05). Should record an
        # anomaly but still parse correctly.
        buf = b"\x30\x81\x05hello"
        anomalies: list[DERAnomaly] = []
        _, length, _, _ = read_tlv(buf, 0, anomalies, "test")
        self.assertEqual(length, 5)
        self.assertTrue(
            any(a.kind == "non_minimal_length" for a in anomalies)
        )

    def test_truncated_buffer_raises(self):
        # Just a tag byte, no length.
        with self.assertRaises(ASN1ParseError):
            read_tlv(b"\x30", 0, [], "test")

    def test_empty_buffer_raises(self):
        with self.assertRaises(ASN1ParseError):
            read_tlv(b"", 0, [], "test")

    def test_offset_past_end_raises(self):
        with self.assertRaises(ASN1ParseError):
            read_tlv(b"\x30\x00", 5, [], "test")

    def test_long_form_octets_overrun_raises(self):
        # 84 = "next 4 octets are length", but we only have 2.
        with self.assertRaises(ASN1ParseError):
            read_tlv(b"\x30\x84\x00\x00", 0, [], "test")


# ---------------------------------------------------------------------------
# OID decoder
# ---------------------------------------------------------------------------

class TestReadOID(unittest.TestCase):
    """OID round-trips covering small arcs, large arcs, edge cases."""

    def test_rsa_encryption_oid(self):
        # 1.2.840.113549.1.1.1
        encoded = bytes.fromhex("2a864886f70d010101")
        self.assertEqual(read_oid(encoded, [], "t"), "1.2.840.113549.1.1.1")

    def test_two_arc_minimal(self):
        # 1.2 -> 0x2a
        self.assertEqual(read_oid(b"\x2a", [], "t"), "1.2")

    def test_first_arc_zero(self):
        # 0.9 -> 0x09
        self.assertEqual(read_oid(b"\x09", [], "t"), "0.9")

    def test_first_arc_two(self):
        # 2.5.4.3 (commonName) -> 0x55 0x04 0x03
        self.assertEqual(read_oid(b"\x55\x04\x03", [], "t"), "2.5.4.3")

    def test_large_arc_uses_continuation(self):
        # Arc value 113549 = 0x1bb8d -> encoded as 86 f7 0d
        encoded = bytes.fromhex("2a864886f70d")
        result = read_oid(encoded, [], "t")
        self.assertTrue(result.startswith("1.2.840.113549"))

    def test_empty_input_records_anomaly(self):
        anomalies: list[DERAnomaly] = []
        result = read_oid(b"", anomalies, "t")
        self.assertEqual(result, "")
        self.assertTrue(any(a.kind == "empty_oid" for a in anomalies))

    def test_truncated_oid_records_anomaly(self):
        # 0x80 has continuation bit set but is the last byte.
        anomalies: list[DERAnomaly] = []
        result = read_oid(b"\x2a\x80", anomalies, "t")
        self.assertIn("[?]", result)
        self.assertTrue(any(a.kind == "truncated_oid" for a in anomalies))


# ---------------------------------------------------------------------------
# INTEGER decoders
# ---------------------------------------------------------------------------

class TestReadIntegerUnsigned(unittest.TestCase):
    """Unsigned INTEGER decoding with sign-byte handling."""

    def test_zero(self):
        self.assertEqual(read_integer_unsigned(b"\x00", [], "t"), 0)

    def test_small_positive(self):
        self.assertEqual(read_integer_unsigned(b"\x42", [], "t"), 0x42)

    def test_max_byte_no_sign(self):
        self.assertEqual(read_integer_unsigned(b"\x7f", [], "t"), 0x7f)

    def test_high_bit_with_sign_byte(self):
        # 0x80 alone would be negative in signed interpretation, so
        # the canonical encoding is 00 80.
        self.assertEqual(read_integer_unsigned(b"\x00\x80", [], "t"), 0x80)

    def test_non_minimal_sign_byte_records_anomaly(self):
        # Leading 0x00 when not needed (next byte's high bit not set).
        anomalies: list[DERAnomaly] = []
        result = read_integer_unsigned(b"\x00\x42", anomalies, "t")
        self.assertEqual(result, 0x42)
        self.assertTrue(
            any(a.kind == "non_minimal_integer" for a in anomalies)
        )

    def test_empty_records_anomaly(self):
        anomalies: list[DERAnomaly] = []
        result = read_integer_unsigned(b"", anomalies, "t")
        self.assertEqual(result, 0)
        self.assertTrue(any(a.kind == "empty_integer" for a in anomalies))

    def test_large_modulus_size(self):
        # Sanity: a 256-byte (2048-bit) modulus decodes to a big int.
        modulus_bytes = b"\x00" + b"\xff" * 256
        result = read_integer_unsigned(modulus_bytes, [], "t")
        self.assertEqual(result.bit_length(), 2048)


class TestReadIntegerSigned(unittest.TestCase):
    """Signed INTEGER decoding (two's complement)."""

    def test_zero(self):
        self.assertEqual(read_integer_signed(b"\x00", [], "t"), 0)

    def test_positive(self):
        self.assertEqual(read_integer_signed(b"\x42", [], "t"), 0x42)

    def test_negative_one(self):
        self.assertEqual(read_integer_signed(b"\xff", [], "t"), -1)

    def test_negative_large(self):
        # 0x80 = -128
        self.assertEqual(read_integer_signed(b"\x80", [], "t"), -128)

    def test_empty_records_anomaly(self):
        anomalies: list[DERAnomaly] = []
        result = read_integer_signed(b"", anomalies, "t")
        self.assertEqual(result, 0)
        self.assertTrue(any(a.kind == "empty_integer" for a in anomalies))


# ---------------------------------------------------------------------------
# String decoders
# ---------------------------------------------------------------------------

class TestReadUtf8String(unittest.TestCase):

    def test_ascii_round_trips(self):
        self.assertEqual(read_utf8_string(b"hello", [], "t"), "hello")

    def test_multibyte_utf8(self):
        # "e-acute" = U+00E9 = 0xc3 0xa9 in UTF-8
        self.assertEqual(read_utf8_string(b"caf\xc3\xa9", [], "t"), "café")

    def test_invalid_utf8_records_anomaly(self):
        anomalies: list[DERAnomaly] = []
        # 0xff is never valid in UTF-8.
        result = read_utf8_string(b"bad\xff", anomalies, "t")
        self.assertTrue(
            any(a.kind == "string_decode_failed" for a in anomalies)
        )
        # Fallback decoded the bytes as latin-1.
        self.assertIn("bad", result)


class TestReadPrintableString(unittest.TestCase):

    def test_alphanumeric_clean(self):
        self.assertEqual(
            read_printable_string(b"hello world", [], "t"),
            "hello world",
        )

    def test_charset_violation_recorded(self):
        # "@" is not in PrintableString's allowed charset.
        anomalies: list[DERAnomaly] = []
        result = read_printable_string(b"a@b", anomalies, "t")
        self.assertEqual(result, "a@b")
        self.assertTrue(
            any(a.kind == "string_charset_violation" for a in anomalies)
        )

    def test_non_ascii_bytes_recorded(self):
        anomalies: list[DERAnomaly] = []
        read_printable_string(b"\xc3\xa9", anomalies, "t")
        self.assertTrue(
            any(a.kind == "string_decode_failed" for a in anomalies)
        )


class TestReadIa5String(unittest.TestCase):

    def test_ascii_clean(self):
        self.assertEqual(
            read_ia5_string(b"admin@example.com", [], "t"),
            "admin@example.com",
        )

    def test_high_bit_records_anomaly(self):
        anomalies: list[DERAnomaly] = []
        read_ia5_string(b"valid\x80byte", anomalies, "t")
        self.assertTrue(
            any(a.kind == "string_charset_violation" for a in anomalies)
        )


class TestReadBmpString(unittest.TestCase):

    def test_ascii_in_bmp(self):
        # "AB" in UTF-16BE = 00 41 00 42
        self.assertEqual(
            read_bmp_string(b"\x00\x41\x00\x42", [], "t"),
            "AB",
        )

    def test_unicode_in_bmp(self):
        # "e-acute" in UTF-16BE = 00 e9
        self.assertEqual(read_bmp_string(b"\x00\xe9", [], "t"), "é")

    def test_odd_length_records_anomaly(self):
        anomalies: list[DERAnomaly] = []
        read_bmp_string(b"\x00\x41\x00", anomalies, "t")
        self.assertTrue(
            any(a.kind == "string_decode_failed" for a in anomalies)
        )


class TestReadT61String(unittest.TestCase):

    def test_always_records_ambiguity_anomaly(self):
        anomalies: list[DERAnomaly] = []
        result = read_t61_string(b"hello", anomalies, "t")
        self.assertEqual(result, "hello")
        self.assertTrue(any(a.kind == "t61_ambiguous" for a in anomalies))


# ---------------------------------------------------------------------------
# Date decoders
# ---------------------------------------------------------------------------

class TestReadUtcTime(unittest.TestCase):

    def test_modern_year(self):
        # 250101000000Z -> 2025-01-01T00:00:00+00:00
        result = read_utc_time(b"250101000000Z", [], "t")
        self.assertEqual(result, "2025-01-01T00:00:00+00:00")

    def test_century_pivot_below_50(self):
        # YY 49 -> 2049
        result = read_utc_time(b"491231235959Z", [], "t")
        self.assertTrue(result.startswith("2049"))

    def test_century_pivot_above_50(self):
        # YY 50 -> 1950
        result = read_utc_time(b"500101000000Z", [], "t")
        self.assertTrue(result.startswith("1950"))

    def test_malformed_records_anomaly(self):
        anomalies: list[DERAnomaly] = []
        read_utc_time(b"not-a-date", anomalies, "t")
        self.assertTrue(
            any(a.kind == "time_format_violation" for a in anomalies)
        )

    def test_invalid_month_records_anomaly(self):
        anomalies: list[DERAnomaly] = []
        read_utc_time(b"251301000000Z", anomalies, "t")
        self.assertTrue(
            any(a.kind == "time_format_violation" for a in anomalies)
        )


class TestReadGeneralizedTime(unittest.TestCase):

    def test_normal_year(self):
        result = read_generalized_time(b"20250101000000Z", [], "t")
        self.assertEqual(result, "2025-01-01T00:00:00+00:00")

    def test_year_9999_sentinel(self):
        # The X.509 "no expiration" convention.
        result = read_generalized_time(b"99991231235959Z", [], "t")
        self.assertEqual(result, "9999-12-31T23:59:59+00:00")

    def test_malformed_records_anomaly(self):
        anomalies: list[DERAnomaly] = []
        read_generalized_time(b"bogus", anomalies, "t")
        self.assertTrue(
            any(a.kind == "time_format_violation" for a in anomalies)
        )


# ---------------------------------------------------------------------------
# looks_like_der pre-check
# ---------------------------------------------------------------------------

class TestLooksLikeDER(unittest.TestCase):

    def test_empty_is_false(self):
        self.assertFalse(looks_like_der(b""))

    def test_one_byte_is_false(self):
        self.assertFalse(looks_like_der(b"\x30"))

    def test_sequence_tag_is_true(self):
        self.assertTrue(looks_like_der(b"\x30\x00"))

    def test_sequence_tag_with_garbage_is_true(self):
        # We don't validate beyond first-byte check; classify() does.
        self.assertTrue(looks_like_der(b"\x30\xff\xff\xff"))

    def test_other_tag_is_false(self):
        self.assertFalse(looks_like_der(b"\x02\x01\x42"))
        self.assertFalse(looks_like_der(b"\x04\x01\x42"))
        self.assertFalse(looks_like_der(b"\x06\x01\x42"))

    def test_random_bytes_is_false(self):
        self.assertFalse(looks_like_der(b"hello world"))


# ---------------------------------------------------------------------------
# classify(): top-level anomaly paths
# ---------------------------------------------------------------------------

class TestClassifyAnomalies(unittest.TestCase):
    """classify() should never raise; every malformed input gets an anomaly."""

    def test_empty_input(self):
        result = classify(b"")
        self.assertEqual(result.kind, "unknown_der")
        self.assertTrue(any(a.kind == "too_short" for a in result.anomalies))

    def test_one_byte_input(self):
        result = classify(b"\x30")
        self.assertEqual(result.kind, "unknown_der")
        self.assertTrue(any(a.kind == "too_short" for a in result.anomalies))

    def test_outer_not_sequence(self):
        # INTEGER (0x02) not SEQUENCE (0x30).
        result = classify(b"\x02\x01\x42")
        self.assertEqual(result.kind, "unknown_der")
        self.assertTrue(
            any(a.kind == "not_sequence" for a in result.anomalies)
        )

    def test_unknown_inner_shape(self):
        # SEQUENCE { INTEGER 1 } - too small to be a cert or SPKI.
        result = classify(b"\x30\x03\x02\x01\x01")
        self.assertEqual(result.kind, "unknown_der")

    def test_truncated_inner(self):
        # SEQUENCE claims 100 bytes but provides only the tag.
        result = classify(b"\x30\x64")
        # Should not raise; should record overrun and fall through.
        self.assertEqual(result.kind, "unknown_der")

    def test_extra_trailing_bytes_recorded(self):
        # Valid empty SEQUENCE with garbage tail.
        result = classify(b"\x30\x00garbage")
        self.assertTrue(
            any(a.kind == "extra_trailing_bytes" for a in result.anomalies)
        )

    def test_classify_never_raises_on_random_garbage(self):
        # Stress check: feed the classifier random byte sequences
        # starting with the SEQUENCE tag to make sure we never raise.
        # subTest gives per-iteration failure context.
        for i in range(20):
            with self.subTest(iteration=i):
                payload = b"\x30" + os.urandom(63)
                result = classify(payload)
                self.assertIsInstance(result, DERClassification)
                self.assertIsInstance(result, FormatContext)


# ---------------------------------------------------------------------------
# classify(): SubjectPublicKeyInfo dispatch
# ---------------------------------------------------------------------------

class TestClassifySPKI(unittest.TestCase):
    """Standalone SPKI dispatch (input is not a cert)."""

    @classmethod
    def setUpClass(cls):
        cls.spki_result = classify(SPKI_RSA_2048)

    def test_rsa_2048_clean(self):
        self.assertEqual(self.spki_result.kind, "rsa_public_key")
        self.assertEqual(self.spki_result.bit_size, 2048)
        self.assertEqual(
            self.spki_result.fields["spki_algorithm_oid"],
            "1.2.840.113549.1.1.1",
        )
        self.assertEqual(
            self.spki_result.fields["rsa_modulus_bits"], "2048",
        )
        self.assertEqual(self.spki_result.fields["rsa_exponent"], "65537")
        self.assertEqual(self.spki_result.anomalies, ())

    def test_rsa_oid_appears_in_oids_seen(self):
        self.assertIn("1.2.840.113549.1.1.1", self.spki_result.oids_seen)

    def test_unknown_algorithm_oid(self):
        # Construct an SPKI shape where the algorithm OID is bogus.
        # 30 LL                          # outer SEQUENCE
        #   30 LL                        # AlgorithmIdentifier SEQUENCE
        #     06 03 99 99 99             # bogus OID: 3.81.1561 (high arcs)
        #   03 02 00 00                  # empty BIT STRING
        bogus_alg = b"\x30\x05\x06\x03\x99\x99\x99"
        bit_string = b"\x03\x02\x00\x00"
        body = bogus_alg + bit_string
        spki = bytes([0x30, len(body)]) + body
        result = classify(spki)
        self.assertEqual(result.kind, "unknown_public_key")


# ---------------------------------------------------------------------------
# classify(): X.509 certificate dispatch
# ---------------------------------------------------------------------------

class TestClassifyX509VanillaCert(unittest.TestCase):
    """The simplest cert: RSA-2048, no extensions, no SAN."""

    @classmethod
    def setUpClass(cls):
        cls.result = classify(CERT_VANILLA_RSA2048)

    def test_kind(self):
        self.assertEqual(self.result.kind, "x509_certificate")

    def test_no_anomalies(self):
        self.assertEqual(self.result.anomalies, ())

    def test_version(self):
        self.assertEqual(self.result.fields["cert_version"], "v3")

    def test_serial(self):
        self.assertEqual(self.result.fields["cert_serial"], "12345")

    def test_signature_algorithm(self):
        # sha256WithRSAEncryption
        self.assertEqual(
            self.result.fields["cert_signature_oid"],
            "1.2.840.113549.1.1.11",
        )

    def test_subject_attrs(self):
        self.assertEqual(
            self.result.fields["cert_subject_cn"], "test.example.com",
        )
        self.assertEqual(self.result.fields["cert_subject_o"], "Test Org")
        self.assertEqual(
            self.result.fields["cert_subject_ou"], "Test Unit",
        )
        self.assertEqual(self.result.fields["cert_subject_c"], "US")

    def test_self_signed_issuer_matches_subject(self):
        self.assertEqual(
            self.result.fields["cert_issuer_cn"],
            self.result.fields["cert_subject_cn"],
        )

    def test_validity_dates(self):
        self.assertEqual(
            self.result.fields["cert_not_before"],
            "2025-01-01T00:00:00+00:00",
        )
        self.assertEqual(
            self.result.fields["cert_not_after"],
            "2026-01-01T00:00:00+00:00",
        )

    def test_rsa_modulus_size(self):
        self.assertEqual(self.result.bit_size, 2048)
        self.assertEqual(
            self.result.fields["cert_rsa_modulus_bits"], "2048",
        )

    def test_no_extensions(self):
        self.assertEqual(self.result.extensions, ())

    def test_no_san(self):
        self.assertEqual(self.result.san_entries, ())

    def test_is_format_context_subclass(self):
        self.assertIsInstance(self.result, FormatContext)


class TestClassifyX509RichSAN(unittest.TestCase):
    """Cert with populated SAN and four extensions."""

    @classmethod
    def setUpClass(cls):
        cls.result = classify(CERT_RICH_SAN)

    def test_kind(self):
        self.assertEqual(self.result.kind, "x509_certificate")

    def test_no_anomalies(self):
        self.assertEqual(self.result.anomalies, ())

    def test_subject_cn(self):
        self.assertEqual(
            self.result.fields["cert_subject_cn"], "richcert.example.com",
        )

    def test_serial(self):
        self.assertEqual(self.result.fields["cert_serial"], "67890")

    def test_extensions_count(self):
        # SAN, BasicConstraints, KeyUsage, ExtendedKeyUsage.
        self.assertEqual(len(self.result.extensions), 4)

    def test_extension_oids(self):
        oids = {e.oid for e in self.result.extensions}
        self.assertIn("2.5.29.17", oids)   # SAN
        self.assertIn("2.5.29.19", oids)   # BasicConstraints
        self.assertIn("2.5.29.15", oids)   # KeyUsage
        self.assertIn("2.5.29.37", oids)   # ExtKeyUsage

    def test_basic_constraints_critical(self):
        bc = next(
            e for e in self.result.extensions if e.oid == "2.5.29.19"
        )
        self.assertTrue(bc.critical)

    def test_key_usage_critical(self):
        ku = next(
            e for e in self.result.extensions if e.oid == "2.5.29.15"
        )
        self.assertTrue(ku.critical)

    def test_san_not_critical(self):
        san = next(
            e for e in self.result.extensions if e.oid == "2.5.29.17"
        )
        self.assertFalse(san.critical)

    def test_extension_value_hex_present(self):
        # Every extension surfaces its raw value bytes for downstream
        # analyzers that want to inspect contents we did not parse.
        for ext in self.result.extensions:
            self.assertIsInstance(ext.value_hex, str)
            self.assertGreater(len(ext.value_hex), 0)
            self.assertTrue(
                all(c in "0123456789abcdef" for c in ext.value_hex)
            )

    def test_san_entries_count(self):
        # 2 dns + 1 uri + 1 email + 1 ip = 5
        self.assertEqual(len(self.result.san_entries), 5)

    def test_san_dns_entries(self):
        dns = [s.value for s in self.result.san_entries if s.kind == "dns"]
        self.assertIn("alt1.example.com", dns)
        self.assertIn("alt2.example.com", dns)

    def test_san_uri_entry(self):
        uris = [s.value for s in self.result.san_entries if s.kind == "uri"]
        self.assertEqual(uris, ["https://example.com/cert"])

    def test_san_email_entry(self):
        emails = [
            s.value for s in self.result.san_entries if s.kind == "email"
        ]
        self.assertEqual(emails, ["admin@example.com"])

    def test_san_ip_entry(self):
        ips = [s.value for s in self.result.san_entries if s.kind == "ip"]
        self.assertEqual(ips, ["192.0.2.42"])

    def test_san_attached_to_san_extension(self):
        # The same SAN entries should be attached to the SAN extension
        # itself (so analyzers can find them either way).
        san_ext = next(
            e for e in self.result.extensions if e.oid == "2.5.29.17"
        )
        self.assertIsNotNone(san_ext.san_entries)
        self.assertEqual(len(san_ext.san_entries), 5)


class TestClassifyX509Suspicious(unittest.TestCase):
    """Cert with deliberately weird-looking but spec-valid features."""

    @classmethod
    def setUpClass(cls):
        cls.result = classify(CERT_SUSPICIOUS)

    def test_kind(self):
        self.assertEqual(self.result.kind, "x509_certificate")

    def test_no_anomalies(self):
        # Spec-valid even if the contents are suspicious; the parser
        # should not flag this with anomalies. Suspicion is the
        # analyzer's call, not the parser's.
        self.assertEqual(self.result.anomalies, ())

    def test_high_entropy_cn_extracted(self):
        self.assertEqual(
            self.result.fields["cert_subject_cn"],
            "x7Kp9mZ4nQrT2vWy8AbCdEfGhJkLmNoPqRsTuVwXyZ123456789",
        )

    def test_large_serial(self):
        # 0xdeadbeefcafebabe = 16045690984503098046
        self.assertEqual(
            self.result.fields["cert_serial"], "16045690984503098046",
        )

    def test_rsa_4096(self):
        self.assertEqual(self.result.bit_size, 4096)

    def test_not_before_utc_time(self):
        # Issued in 2025, encoded as UTCTime.
        self.assertEqual(
            self.result.fields["cert_not_before"],
            "2025-01-01T00:00:00+00:00",
        )

    def test_not_after_generalized_time_year_9999(self):
        # Beyond UTCTime range (>= 2050), so encoded as GeneralizedTime.
        # This is the X.509 "no expiration" sentinel.
        self.assertEqual(
            self.result.fields["cert_not_after"],
            "9999-12-31T23:59:59+00:00",
        )

    def test_san_count(self):
        # 1 DNS + 1 otherName.
        self.assertEqual(len(self.result.san_entries), 2)

    def test_san_dns_entry(self):
        dns = [s for s in self.result.san_entries if s.kind == "dns"]
        self.assertEqual(len(dns), 1)
        self.assertEqual(dns[0].value, "totallynotac2.example.com")

    def test_san_other_name_entry(self):
        others = [
            s for s in self.result.san_entries if s.kind == "other_name"
        ]
        self.assertEqual(len(others), 1)
        # The custom OID should be surfaced on type_id.
        self.assertEqual(others[0].type_id, "1.3.6.1.4.1.99999.1.2.3")

    def test_critical_unrecognized_extension_present(self):
        # A critical extension with an OID we have no built-in semantics
        # for is exactly the kind of thing an analyzer wants to flag.
        # The parser surfaces it; the analyzer decides what to do.
        unknown = next(
            e for e in self.result.extensions
            if e.oid == "1.3.6.1.4.1.99999.7.7.7"
        )
        self.assertTrue(unknown.critical)
        self.assertGreater(len(unknown.value_hex), 0)

    def test_oids_seen_includes_custom(self):
        # The custom extension OID and the otherName OID should both
        # show up in oids_seen (analyzers can treat oids_seen as a
        # cheap "is anything weird in here" filter).
        self.assertIn("1.3.6.1.4.1.99999.7.7.7", self.result.oids_seen)
        self.assertIn("1.3.6.1.4.1.99999.1.2.3", self.result.oids_seen)


# ---------------------------------------------------------------------------
# FormatContext marker class
# ---------------------------------------------------------------------------

class TestFormatContextMarker(unittest.TestCase):
    """The marker pattern: DERClassification IS-A FormatContext."""

    def test_classification_is_format_context(self):
        result = classify(CERT_VANILLA_RSA2048)
        self.assertIsInstance(result, FormatContext)
        self.assertIsInstance(result, DERClassification)

    def test_format_context_is_frozen(self):
        # Frozen dataclass should reject attribute assignment with
        # FrozenInstanceError. Tests on FormatContext directly to
        # confirm the marker base class itself is frozen, not just
        # the subclass.
        ctx = FormatContext()
        with self.assertRaises(dataclasses.FrozenInstanceError):
            ctx.some_field = "value"

    def test_classification_subclass_is_frozen(self):
        # Same property inherited by subclasses: assigning to a
        # known field also raises.
        result = classify(CERT_VANILLA_RSA2048)
        with self.assertRaises(dataclasses.FrozenInstanceError):
            result.kind = "other"

    def test_subclass_picklable(self):
        # The dataclass shape is supposed to pickle cleanly so
        # results can be cached or sent across processes.
        result = classify(CERT_VANILLA_RSA2048)
        roundtripped = pickle.loads(pickle.dumps(result))
        self.assertEqual(roundtripped.kind, result.kind)
        self.assertEqual(roundtripped.fields, result.fields)


if __name__ == "__main__":
    unittest.main()