"""pydepgate.events.__init__

Event handling for pydepgate.

Intent: This is the main module of the event handling for pydepgate.

How it works: The event handling module receives events from various components of the system and processes them accordingly.

Workflows:

(event)
1. An event is received
2. The event is processed by the appropriate handler
3. The result is returned to the caller

Expectations:
1. Events are processed in the order they are received
2. Each event is handled by the appropriate handler based on its type
3. The result of each event is returned to the caller
4. The event handling module should be able to handle multiple events concurrently without blocking.
5. The event handling module should be able to handle events of different types without conflicts.
6. The event handling module should be able to handle errors gracefully and provide meaningful error messages.
7. The event handling module should be able to log events for debugging and monitoring purposes.
8. The event handling module SHOULD NEVER return raw payload bytes from scan materials to the caller. EVER.

Taxonomy:
Event: A notification or signal that is sent from one component of the system to another.
Event Classification: Events can be classified based on their type, priority, and the component that generated them.
    - Internal Events: Events generated within the system. Always start with internal.*
        - System Events: Events that are generated by the system itself, such as startup, shutdown, or configuration changes. Will always be internal.system.*
        - Scan Events: Events that are generated during the scanning of materials. Will always be internal.scanner.*
        - Policy Events: Events that are generated when a policy is triggered or updated. Will always be internal.policy.*
        - Enrichment Events: Events that are generated during the enrichment of materials. Will always be internal.enrichers.*
        - Workplan Events [future]: Events that are generated during the execution of workplans. Will always be internal.workplan.*
            - IMPORTANT: Workplan events CAN call external tools, but the workplan event calling the external tool will ALWAYS be internal.workplan.*
        - More event types will be added in the future.
    - External Events: Events generated from external sources. Always start with external.*
        - This will typically only be used by workplan.
Sinkmap: A configuration file that pydepgate.auditd uses to map pydepgate native fields to external expectations.
Event ID: A uuid7 identifier for each event. Will never repeat.
Correlation ID: A unique identifier used to correlate related events. This can be useful for debugging and tracing the flow of events through the system.
    This is typically the Scan ID, but can be any unique identifier that helps in correlating events.
Handler: Who generated the event.
Receiver: Who is expected to receive the event, if known or applicable.
Payload: The data associated with the event. Will always be structured JSON.
mTLS: Mutual Transport Layer Security, a security protocol that provides authentication and encryption for communication between two parties. Used by pydepgate for external communication for security purposes.
Workplan [future]: A configuration or plan for executing tasks or processes. This is the grand orchestration layer for the system, and can call both pydepgate internal tools and external tools via toolmaps and configurations in a workplan blueprint.


"""

from pydepgate.events.emitter import EventEmitter, EventEmitterError
from pydepgate.events.envelope import EventEnvelope, EventEnvelopeError
from pydepgate.events.freeze import DeepFreezeError, FrozenMapping, deep_freeze
from pydepgate.events.sinks import (
    EventSink,
    EventSinkError,
    JsonlEventSink,
    MemoryEventSink,
    NullEventSink,
    TeeEventSink,
)
from pydepgate.events.tickets import (
    LocalInvocationError,
    ScanGrantingTicket,
    ScanGrantingTicketError,
    mintsgt,
)

__all__ = [
    "EventEnvelope",
    "EventEnvelopeError",
    "EventEmitter",
    "EventEmitterError",
    "EventSink",
    "EventSinkError",
    "JsonlEventSink",
    "MemoryEventSink",
    "NullEventSink",
    "TeeEventSink",
    "DeepFreezeError",
    "FrozenMapping",
    "deep_freeze",
    "LocalInvocationError",
    "ScanGrantingTicket",
    "ScanGrantingTicketError",
    "mintsgt",
]
