title: pydepgate
description: Static analyzer for Python supply-chain malware targeting interpreter startup vectors.
repository: nuclear-treestump/pydepgate
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme

color_scheme: dark
search_enabled: true
enable_copy_code_button: true

aux_links:
  "View on GitHub":
    - "https://github.com/nuclear-treestump/pydepgate"

